<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE school [
    <!ELEMENT school (class*)>
    <!ELEMENT class (teacher,student+)>
    <!ELEMENT teacher (sex*)>
    <!ELEMENT student (sex*)>
    <!ELEMENT sex (#PCDATA)>

    <!ATTLIST school
            name CDATA #REQUIRED
    >
    <!ATTLIST class
            classId CDATA #REQUIRED
    >
    <!ATTLIST teacher
            age CDATA #IMPLIED
            name CDATA #REQUIRED
            price CDATA #IMPLIED
    >
]>

<school name="">
    <class classId="">
        <teacher age="" name="" price="">
            <sex>ç”·</sex>
        </teacher>
        <student></student>
        <student></student>
    </class>

    <class classId="">
        <teacher name=""></teacher>
        <student></student>
        <student></student>
    </class>
</school>